// Mocks generated by Mockito 5.4.6 from annotations
// in sorutrack_pro/test/widget/features/auth/onboarding_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sorutrack_pro/core/error/failures.dart' as _i6;
import 'package:sorutrack_pro/core/services/gemini_key_service.dart' as _i8;
import 'package:sorutrack_pro/features/auth/domain/models/user_profile.dart'
    as _i7;
import 'package:sorutrack_pro/features/auth/domain/repositories/user_repository.dart'
    as _i2;
import 'package:sorutrack_pro/features/auth/domain/usecases/profile_use_cases.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserRepository_0 extends _i1.SmartFake
    implements _i2.UserRepository {
  _FakeUserRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SaveUserProfile].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveUserProfile extends _i1.Mock implements _i4.SaveUserProfile {
  MockSaveUserProfile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUserRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.UserRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>> call(
    _i7.UserProfile? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [profile]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>.value(
              _FakeEither_1<_i6.Failure, _i3.Unit>(
                this,
                Invocation.method(#call, [profile]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>);
}

/// A class which mocks [GeminiKeyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiKeyService extends _i1.Mock implements _i8.GeminiKeyService {
  MockGeminiKeyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#saveKey, [apiKey]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getKey() =>
      (super.noSuchMethod(
            Invocation.method(#getKey, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> hasKey() =>
      (super.noSuchMethod(
            Invocation.method(#hasKey, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> deleteKey() =>
      (super.noSuchMethod(
            Invocation.method(#deleteKey, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i8.ApiKeyValidationResult> validateKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#validateKey, [apiKey]),
            returnValue: _i5.Future<_i8.ApiKeyValidationResult>.value(
              _i8.ApiKeyValidationResult.valid,
            ),
          )
          as _i5.Future<_i8.ApiKeyValidationResult>);
}
