// Mocks generated by Mockito 5.4.6 from annotations
// in sorutrack_pro/test/unit/features/reports/data/repositories/reports_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sorutrack_pro/core/database/database_helper.dart' as _i3;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i3.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<_i2.Database> openTestDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#openTestDatabase, []),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.method(#openTestDatabase, [])),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<Map<String, dynamic>> getTodayNutrition(
    String? userId,
    String? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTodayNutrition, [userId, date]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<double> getExerciseCaloriesByDate(String? userId, String? date) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseCaloriesByDate, [userId, date]),
            returnValue: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);

  @override
  _i4.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getMealsByDate(
    String? userId,
    String? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMealsByDate, [userId, date]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getMealItemsByMealId(String? mealId) =>
      (super.noSuchMethod(
            Invocation.method(#getMealItemsByMealId, [mealId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getWeeklyCalories(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getWeeklyCalories, [userId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<double> getWaterByDate(String? userId, String? date) =>
      (super.noSuchMethod(
            Invocation.method(#getWaterByDate, [userId, date]),
            returnValue: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);

  @override
  _i4.Future<int> getCurrentStreak(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentStreak, [userId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getCalorieTrend(
    String? userId,
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCalorieTrend, [userId, startDate, endDate]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getMacroTrend(
    String? userId,
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMacroTrend, [userId, startDate, endDate]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getTopFoods(
    String? userId,
    int? limit,
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTopFoods, [
              userId,
              limit,
              startDate,
              endDate,
            ]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getMealTimingData(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMealTimingData, [userId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getWeightTrend(
    String? userId,
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWeightTrend, [userId, startDate, endDate]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getGoalAdherence(
    String? userId,
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalAdherence, [userId, startDate, endDate]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> getMicronutrientAverages(
    String? userId,
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMicronutrientAverages, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> searchFoodInLog(
    String? userId,
    String? query, {
    String? startDate,
    String? endDate,
    List<String>? mealTypes,
    double? minCalories,
    double? maxCalories,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchFoodInLog,
              [userId, query],
              {
                #startDate: startDate,
                #endDate: endDate,
                #mealTypes: mealTypes,
                #minCalories: minCalories,
                #maxCalories: maxCalories,
              },
            ),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> logWater(String? userId, String? date, double? amountMl) =>
      (super.noSuchMethod(
            Invocation.method(#logWater, [userId, date, amountMl]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
