// Mocks generated by Mockito 5.4.6 from annotations
// in sorutrack_pro/test/unit/features/dashboard/dashboard_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sorutrack_pro/core/error/failures.dart' as _i5;
import 'package:sorutrack_pro/core/services/home_widget_service.dart' as _i7;
import 'package:sorutrack_pro/features/dashboard/domain/models/dashboard_data.dart'
    as _i6;
import 'package:sorutrack_pro/features/dashboard/domain/repositories/dashboard_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DashboardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardRepository extends _i1.Mock
    implements _i3.DashboardRepository {
  MockDashboardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.DashboardData>> getDashboardData(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardData, [userId, date]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.DashboardData>>.value(
                  _FakeEither_0<_i5.Failure, _i6.DashboardData>(
                    this,
                    Invocation.method(#getDashboardData, [userId, date]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.DashboardData>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WeeklyCalorieData>>>
  getWeeklyCalories(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getWeeklyCalories, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.WeeklyCalorieData>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.WeeklyCalorieData>>(
                    this,
                    Invocation.method(#getWeeklyCalories, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WeeklyCalorieData>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> logWater(
    String? userId,
    DateTime? date,
    int? mlToAdd,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logWater, [userId, date, mlToAdd]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#logWater, [userId, date, mlToAdd]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [HomeWidgetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeWidgetService extends _i1.Mock implements _i7.HomeWidgetService {
  MockHomeWidgetService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> updateWidget({
    required int? streak,
    double? caloriesConsumed,
    double? calorieTarget,
    String? remainingCalories,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateWidget, [], {
              #streak: streak,
              #caloriesConsumed: caloriesConsumed,
              #calorieTarget: calorieTarget,
              #remainingCalories: remainingCalories,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
