// Mocks generated by Mockito 5.4.6 from annotations
// in sorutrack_pro/test/unit/features/meal_log/data/gemini_meal_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:google_generative_ai/google_generative_ai.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sorutrack_pro/core/services/gemini_client.dart' as _i4;
import 'package:sorutrack_pro/core/services/gemini_key_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GeminiKeyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiKeyService extends _i1.Mock implements _i2.GeminiKeyService {
  MockGeminiKeyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#saveKey, [apiKey]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getKey() =>
      (super.noSuchMethod(
            Invocation.method(#getKey, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> hasKey() =>
      (super.noSuchMethod(
            Invocation.method(#hasKey, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteKey() =>
      (super.noSuchMethod(
            Invocation.method(#deleteKey, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.ApiKeyValidationResult> validateKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#validateKey, [apiKey]),
            returnValue: _i3.Future<_i2.ApiKeyValidationResult>.value(
              _i2.ApiKeyValidationResult.valid,
            ),
          )
          as _i3.Future<_i2.ApiKeyValidationResult>);
}

/// A class which mocks [GeminiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiClient extends _i1.Mock implements _i4.GeminiClient {
  MockGeminiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> generateContent({
    required String? apiKey,
    required String? modelName,
    required Iterable<_i5.Content>? content,
    _i5.GenerationConfig? generationConfig,
    List<_i5.SafetySetting>? safetySettings,
    List<_i5.Tool>? tools,
    _i5.ToolConfig? toolConfig,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateContent, [], {
              #apiKey: apiKey,
              #modelName: modelName,
              #content: content,
              #generationConfig: generationConfig,
              #safetySettings: safetySettings,
              #tools: tools,
              #toolConfig: toolConfig,
            }),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}
