// Mocks generated by Mockito 5.4.6 from annotations
// in sorutrack_pro/test/unit/features/notifications/data/services/notification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sorutrack_pro/features/notifications/data/services/notification_service.dart'
    as _i2;
import 'package:timezone/timezone.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i2.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllNotifications, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelNotification(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelNotification, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> showNotification({
    required int? id,
    required String? title,
    required String? body,
    String? payload,
    String? channelId = 'meal_reminders',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showNotification, [], {
              #id: id,
              #title: title,
              #body: body,
              #payload: payload,
              #channelId: channelId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> scheduleNotification({
    required int? id,
    required String? title,
    required String? body,
    required DateTime? scheduledDate,
    String? channelId = 'meal_reminders',
    _i4.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleNotification, [], {
              #id: id,
              #title: title,
              #body: body,
              #scheduledDate: scheduledDate,
              #channelId: channelId,
              #matchDateTimeComponents: matchDateTimeComponents,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> scheduleMealReminders() =>
      (super.noSuchMethod(
            Invocation.method(#scheduleMealReminders, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelMealReminders() =>
      (super.noSuchMethod(
            Invocation.method(#cancelMealReminders, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> scheduleWaterReminders() =>
      (super.noSuchMethod(
            Invocation.method(#scheduleWaterReminders, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelWaterReminders() =>
      (super.noSuchMethod(
            Invocation.method(#cancelWaterReminders, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i4.FlutterLocalNotificationsPlugin {
  @override
  _i3.Future<bool?> initialize({
    required _i4.InitializationSettings? settings,
    _i4.DidReceiveNotificationResponseCallback?
    onDidReceiveNotificationResponse,
    _i4.DidReceiveBackgroundNotificationResponseCallback?
    onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #settings: settings,
              #onDidReceiveNotificationResponse:
                  onDidReceiveNotificationResponse,
              #onDidReceiveBackgroundNotificationResponse:
                  onDidReceiveBackgroundNotificationResponse,
            }),
            returnValue: _i3.Future<bool?>.value(),
            returnValueForMissingStub: _i3.Future<bool?>.value(),
          )
          as _i3.Future<bool?>);

  @override
  _i3.Future<_i4.NotificationAppLaunchDetails?>
  getNotificationAppLaunchDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationAppLaunchDetails, []),
            returnValue: _i3.Future<_i4.NotificationAppLaunchDetails?>.value(),
            returnValueForMissingStub:
                _i3.Future<_i4.NotificationAppLaunchDetails?>.value(),
          )
          as _i3.Future<_i4.NotificationAppLaunchDetails?>);

  @override
  _i3.Future<void> show({
    required int? id,
    String? title,
    String? body,
    _i4.NotificationDetails? notificationDetails,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#show, [], {
              #id: id,
              #title: title,
              #body: body,
              #notificationDetails: notificationDetails,
              #payload: payload,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancel({required int? id, String? tag}) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [], {#id: id, #tag: tag}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAllPendingNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllPendingNotifications, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> zonedSchedule({
    required int? id,
    required _i5.TZDateTime? scheduledDate,
    required _i4.NotificationDetails? notificationDetails,
    required _i4.AndroidScheduleMode? androidScheduleMode,
    String? title,
    String? body,
    String? payload,
    _i4.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#zonedSchedule, [], {
              #id: id,
              #scheduledDate: scheduledDate,
              #notificationDetails: notificationDetails,
              #androidScheduleMode: androidScheduleMode,
              #title: title,
              #body: body,
              #payload: payload,
              #matchDateTimeComponents: matchDateTimeComponents,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> periodicallyShow({
    required int? id,
    required _i4.RepeatInterval? repeatInterval,
    required _i4.NotificationDetails? notificationDetails,
    required _i4.AndroidScheduleMode? androidScheduleMode,
    String? title,
    String? body,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#periodicallyShow, [], {
              #id: id,
              #repeatInterval: repeatInterval,
              #notificationDetails: notificationDetails,
              #androidScheduleMode: androidScheduleMode,
              #title: title,
              #body: body,
              #payload: payload,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> periodicallyShowWithDuration({
    required int? id,
    required Duration? repeatDurationInterval,
    required _i4.NotificationDetails? notificationDetails,
    String? title,
    String? body,
    _i4.AndroidScheduleMode? androidScheduleMode =
        _i4.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#periodicallyShowWithDuration, [], {
              #id: id,
              #repeatDurationInterval: repeatDurationInterval,
              #notificationDetails: notificationDetails,
              #title: title,
              #body: body,
              #androidScheduleMode: androidScheduleMode,
              #payload: payload,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.PendingNotificationRequest>>
  pendingNotificationRequests() =>
      (super.noSuchMethod(
            Invocation.method(#pendingNotificationRequests, []),
            returnValue: _i3.Future<List<_i4.PendingNotificationRequest>>.value(
              <_i4.PendingNotificationRequest>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.PendingNotificationRequest>>.value(
                  <_i4.PendingNotificationRequest>[],
                ),
          )
          as _i3.Future<List<_i4.PendingNotificationRequest>>);

  @override
  _i3.Future<List<_i4.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveNotifications, []),
            returnValue: _i3.Future<List<_i4.ActiveNotification>>.value(
              <_i4.ActiveNotification>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.ActiveNotification>>.value(
                  <_i4.ActiveNotification>[],
                ),
          )
          as _i3.Future<List<_i4.ActiveNotification>>);
}
