// Mocks generated by Mockito 5.4.6 from annotations
// in sorutrack_pro/test/unit/features/reports/presentation/bloc/reports_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:sorutrack_pro/features/reports/data/services/gemini_reports_service.dart'
    as _i5;
import 'package:sorutrack_pro/features/reports/domain/models/report_models.dart'
    as _i2;
import 'package:sorutrack_pro/features/reports/domain/repositories/reports_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMicronutrientData_0 extends _i1.SmartFake
    implements _i2.MicronutrientData {
  _FakeMicronutrientData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ReportsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportsRepository extends _i1.Mock implements _i3.ReportsRepository {
  MockReportsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ReportTrendData>> getCalorieTrend(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCalorieTrend, [userId, startDate, endDate]),
            returnValue: _i4.Future<List<_i2.ReportTrendData>>.value(
              <_i2.ReportTrendData>[],
            ),
          )
          as _i4.Future<List<_i2.ReportTrendData>>);

  @override
  _i4.Future<List<_i2.MacroDistribution>> getMacroTrend(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMacroTrend, [userId, startDate, endDate]),
            returnValue: _i4.Future<List<_i2.MacroDistribution>>.value(
              <_i2.MacroDistribution>[],
            ),
          )
          as _i4.Future<List<_i2.MacroDistribution>>);

  @override
  _i4.Future<List<_i2.TopFood>> getTopFoods(
    String? userId, {
    int? limit = 10,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getTopFoods,
              [userId],
              {#limit: limit, #startDate: startDate, #endDate: endDate},
            ),
            returnValue: _i4.Future<List<_i2.TopFood>>.value(<_i2.TopFood>[]),
          )
          as _i4.Future<List<_i2.TopFood>>);

  @override
  _i4.Future<List<_i2.MealTimingData>> getMealTimingData(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMealTimingData, [userId]),
            returnValue: _i4.Future<List<_i2.MealTimingData>>.value(
              <_i2.MealTimingData>[],
            ),
          )
          as _i4.Future<List<_i2.MealTimingData>>);

  @override
  _i4.Future<List<_i2.ReportTrendData>> getWeightTrend(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWeightTrend, [userId, startDate, endDate]),
            returnValue: _i4.Future<List<_i2.ReportTrendData>>.value(
              <_i2.ReportTrendData>[],
            ),
          )
          as _i4.Future<List<_i2.ReportTrendData>>);

  @override
  _i4.Future<List<_i2.GoalAdherenceData>> getGoalAdherence(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalAdherence, [userId, startDate, endDate]),
            returnValue: _i4.Future<List<_i2.GoalAdherenceData>>.value(
              <_i2.GoalAdherenceData>[],
            ),
          )
          as _i4.Future<List<_i2.GoalAdherenceData>>);

  @override
  _i4.Future<_i2.MicronutrientData> getMicronutrientAverages(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMicronutrientAverages, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i4.Future<_i2.MicronutrientData>.value(
              _FakeMicronutrientData_0(
                this,
                Invocation.method(#getMicronutrientAverages, [
                  userId,
                  startDate,
                  endDate,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.MicronutrientData>);

  @override
  _i4.Future<List<_i2.FoodLogEntry>> searchFoodEntries(
    String? userId, {
    String? query = '',
    DateTime? startDate,
    DateTime? endDate,
    List<String>? mealTypes,
    double? minCalories,
    double? maxCalories,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchFoodEntries,
              [userId],
              {
                #query: query,
                #startDate: startDate,
                #endDate: endDate,
                #mealTypes: mealTypes,
                #minCalories: minCalories,
                #maxCalories: maxCalories,
              },
            ),
            returnValue: _i4.Future<List<_i2.FoodLogEntry>>.value(
              <_i2.FoodLogEntry>[],
            ),
          )
          as _i4.Future<List<_i2.FoodLogEntry>>);

  @override
  _i4.Future<int> getCurrentStreak(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentStreak, [userId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [GeminiReportsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiReportsService extends _i1.Mock
    implements _i5.GeminiReportsService {
  MockGeminiReportsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> generateWeeklyInsights({
    required List<_i2.ReportTrendData>? calories,
    required List<_i2.MacroDistribution>? macros,
    required List<_i2.TopFood>? topFoods,
    required _i2.MicronutrientData? micros,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateWeeklyInsights, [], {
              #calories: calories,
              #macros: macros,
              #topFoods: topFoods,
              #micros: micros,
            }),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#generateWeeklyInsights, [], {
                  #calories: calories,
                  #macros: macros,
                  #topFoods: topFoods,
                  #micros: micros,
                }),
              ),
            ),
          )
          as _i4.Future<String>);
}
