// Mocks generated by Mockito 5.4.6 from annotations
// in sorutrack_pro/test/unit/features/gamification/gamification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sorutrack_pro/core/error/failures.dart' as _i5;
import 'package:sorutrack_pro/features/gamification/domain/models/gamification_models.dart'
    as _i6;
import 'package:sorutrack_pro/features/gamification/domain/repositories/gamification_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GamificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamificationRepository extends _i1.Mock
    implements _i3.GamificationRepository {
  MockGamificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.GamificationData>> getGamificationData(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGamificationData, [userId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.GamificationData>>.value(
                  _FakeEither_0<_i5.Failure, _i6.GamificationData>(
                    this,
                    Invocation.method(#getGamificationData, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.GamificationData>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateXP(
    String? userId,
    int? amount,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateXP, [userId, amount, reason]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateXP, [userId, amount, reason]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateStreak(
    String? userId,
    bool? increment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateStreak, [userId, increment]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateStreak, [userId, increment]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Badge>>> getBadges() =>
      (super.noSuchMethod(
            Invocation.method(#getBadges, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Badge>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Badge>>(
                    this,
                    Invocation.method(#getBadges, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Badge>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Achievement>>>
  getUserAchievements(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAchievements, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.Achievement>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Achievement>>(
                    this,
                    Invocation.method(#getUserAchievements, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Achievement>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> unlockBadge(
    String? userId,
    String? badgeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#unlockBadge, [userId, badgeId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#unlockBadge, [userId, badgeId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Challenge>>>
  getActiveChallenges() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveChallenges, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Challenge>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Challenge>>(
                    this,
                    Invocation.method(#getActiveChallenges, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Challenge>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserChallenge>>>
  getUserChallenges(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserChallenges, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.UserChallenge>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.UserChallenge>>(
                    this,
                    Invocation.method(#getUserChallenges, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserChallenge>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateChallengeProgress(
    String? userId,
    String? challengeId,
    double? progress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateChallengeProgress, [
              userId,
              challengeId,
              progress,
            ]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateChallengeProgress, [
                  userId,
                  challengeId,
                  progress,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
