// Mocks generated by Mockito 5.4.6 from annotations
// in sorutrack_pro/test/unit/features/meal_log/meal_log_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sorutrack_pro/core/error/failures.dart' as _i5;
import 'package:sorutrack_pro/features/meal_log/domain/models/daily_nutrition.dart'
    as _i7;
import 'package:sorutrack_pro/features/meal_log/domain/models/parsed_meal.dart'
    as _i6;
import 'package:sorutrack_pro/features/meal_log/domain/repositories/meal_repository.dart'
    as _i3;
import 'package:sorutrack_pro/features/reports/domain/models/report_models.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MealRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealRepository extends _i1.Mock implements _i3.MealRepository {
  MockMealRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ParsedMeal>> parseMeal(
    String? input,
    String? mealType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#parseMeal, [input, mealType]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ParsedMeal>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ParsedMeal>(
                    this,
                    Invocation.method(#parseMeal, [input, mealType]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ParsedMeal>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveMeal(_i6.ParsedMeal? meal) =>
      (super.noSuchMethod(
            Invocation.method(#saveMeal, [meal]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#saveMeal, [meal]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ParsedMeal>>> getMealsForDate(
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMealsForDate, [date]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.ParsedMeal>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ParsedMeal>>(
                    this,
                    Invocation.method(#getMealsForDate, [date]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ParsedMeal>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteMeal(String? mealId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMeal, [mealId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteMeal, [mealId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.DailyNutrition>> getTodayNutrition({
    required String? userId,
    required String? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTodayNutrition, [], {
              #userId: userId,
              #date: date,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.DailyNutrition>>.value(
                  _FakeEither_0<_i5.Failure, _i7.DailyNutrition>(
                    this,
                    Invocation.method(#getTodayNutrition, [], {
                      #userId: userId,
                      #date: date,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.DailyNutrition>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.ReportTrendData>>>
  getWeeklyCalories(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getWeeklyCalories, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i8.ReportTrendData>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i8.ReportTrendData>>(
                    this,
                    Invocation.method(#getWeeklyCalories, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.ReportTrendData>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getCurrentStreak(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentStreak, [userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
              _FakeEither_0<_i5.Failure, int>(
                this,
                Invocation.method(#getCurrentStreak, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.FoodLogEntry>>> searchFoodInLog(
    String? userId,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchFoodInLog, [userId, query]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i8.FoodLogEntry>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i8.FoodLogEntry>>(
                    this,
                    Invocation.method(#searchFoodInLog, [userId, query]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.FoodLogEntry>>>);
}
