// Mocks generated by Mockito 5.4.6 from annotations
// in sorutrack_pro/test/unit/features/food/food_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sorutrack_pro/features/food/data/datasources/food_local_data_source.dart'
    as _i2;
import 'package:sorutrack_pro/features/food/data/datasources/food_remote_data_source.dart'
    as _i5;
import 'package:sorutrack_pro/features/food/domain/entities/food_item.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FoodLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodLocalDataSource extends _i1.Mock
    implements _i2.FoodLocalDataSource {
  MockFoodLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.FoodItem>> searchFoods(
    String? query, {
    List<String>? filters,
    String? sortBy,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchFoods,
              [query],
              {
                #filters: filters,
                #sortBy: sortBy,
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i3.Future<List<_i4.FoodItem>>.value(<_i4.FoodItem>[]),
          )
          as _i3.Future<List<_i4.FoodItem>>);

  @override
  _i3.Future<_i4.FoodItem?> getFoodByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodByBarcode, [barcode]),
            returnValue: _i3.Future<_i4.FoodItem?>.value(),
          )
          as _i3.Future<_i4.FoodItem?>);

  @override
  _i3.Future<void> cacheFood(_i4.FoodItem? food) =>
      (super.noSuchMethod(
            Invocation.method(#cacheFood, [food]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.FoodItem>> getRecentFoods() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentFoods, []),
            returnValue: _i3.Future<List<_i4.FoodItem>>.value(<_i4.FoodItem>[]),
          )
          as _i3.Future<List<_i4.FoodItem>>);

  @override
  _i3.Future<List<_i4.FoodItem>> getFrequentFoods() =>
      (super.noSuchMethod(
            Invocation.method(#getFrequentFoods, []),
            returnValue: _i3.Future<List<_i4.FoodItem>>.value(<_i4.FoodItem>[]),
          )
          as _i3.Future<List<_i4.FoodItem>>);

  @override
  _i3.Future<void> saveCustomFood(_i4.FoodItem? food) =>
      (super.noSuchMethod(
            Invocation.method(#saveCustomFood, [food]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleFavorite(String? foodId, bool? isFavorite) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [foodId, isFavorite]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateFoodUseCount(String? foodId) =>
      (super.noSuchMethod(
            Invocation.method(#updateFoodUseCount, [foodId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [FoodRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodRemoteDataSource extends _i1.Mock
    implements _i5.FoodRemoteDataSource {
  MockFoodRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.FoodItem?> getFoodByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodByBarcode, [barcode]),
            returnValue: _i3.Future<_i4.FoodItem?>.value(),
          )
          as _i3.Future<_i4.FoodItem?>);
}
