// Mocks generated by Mockito 5.4.6 from annotations
// in sorutrack_pro/test/integration/web_e2e_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sorutrack_pro/core/error/failures.dart' as _i5;
import 'package:sorutrack_pro/core/services/gemini_key_service.dart' as _i7;
import 'package:sorutrack_pro/features/meal_log/data/gemini_meal_service.dart'
    as _i3;
import 'package:sorutrack_pro/features/meal_log/domain/models/parsed_meal.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GeminiMealService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiMealService extends _i1.Mock implements _i3.GeminiMealService {
  MockGeminiMealService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ParsedMeal>> parseNaturalLanguageMeal(
    String? userInput,
    String? mealType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#parseNaturalLanguageMeal, [userInput, mealType]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ParsedMeal>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ParsedMeal>(
                    this,
                    Invocation.method(#parseNaturalLanguageMeal, [
                      userInput,
                      mealType,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ParsedMeal>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ParsedMeal>> parseWithImage(
    dynamic image,
    String? additionalContext,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#parseWithImage, [image, additionalContext]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ParsedMeal>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ParsedMeal>(
                    this,
                    Invocation.method(#parseWithImage, [
                      image,
                      additionalContext,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ParsedMeal>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ParsedMeal>> correctParsedMeal(
    _i6.ParsedMeal? original,
    String? correction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#correctParsedMeal, [original, correction]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ParsedMeal>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ParsedMeal>(
                    this,
                    Invocation.method(#correctParsedMeal, [
                      original,
                      correction,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ParsedMeal>>);
}

/// A class which mocks [GeminiKeyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiKeyService extends _i1.Mock implements _i7.GeminiKeyService {
  MockGeminiKeyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#saveKey, [apiKey]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getKey() =>
      (super.noSuchMethod(
            Invocation.method(#getKey, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> hasKey() =>
      (super.noSuchMethod(
            Invocation.method(#hasKey, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> deleteKey() =>
      (super.noSuchMethod(
            Invocation.method(#deleteKey, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.ApiKeyValidationResult> validateKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#validateKey, [apiKey]),
            returnValue: _i4.Future<_i7.ApiKeyValidationResult>.value(
              _i7.ApiKeyValidationResult.valid,
            ),
          )
          as _i4.Future<_i7.ApiKeyValidationResult>);
}
