// Mocks generated by Mockito 5.4.6 from annotations
// in sorutrack_pro/test/unit/features/notifications/domain/managers/notification_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sorutrack_pro/features/notifications/data/services/notification_service.dart'
    as _i3;
import 'package:sorutrack_pro/features/notifications/domain/models/notification_settings.dart'
    as _i2;
import 'package:sorutrack_pro/features/notifications/domain/repositories/notification_repository.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNotificationSettings_0 extends _i1.SmartFake
    implements _i2.NotificationSettings {
  _FakeNotificationSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i3.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllNotifications, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelNotification(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelNotification, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> showNotification({
    required int? id,
    required String? title,
    required String? body,
    String? payload,
    String? channelId = 'meal_reminders',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showNotification, [], {
              #id: id,
              #title: title,
              #body: body,
              #payload: payload,
              #channelId: channelId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleNotification({
    required int? id,
    required String? title,
    required String? body,
    required DateTime? scheduledDate,
    String? channelId = 'meal_reminders',
    _i5.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleNotification, [], {
              #id: id,
              #title: title,
              #body: body,
              #scheduledDate: scheduledDate,
              #channelId: channelId,
              #matchDateTimeComponents: matchDateTimeComponents,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleMealReminders() =>
      (super.noSuchMethod(
            Invocation.method(#scheduleMealReminders, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelMealReminders() =>
      (super.noSuchMethod(
            Invocation.method(#cancelMealReminders, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleWaterReminders() =>
      (super.noSuchMethod(
            Invocation.method(#scheduleWaterReminders, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelWaterReminders() =>
      (super.noSuchMethod(
            Invocation.method(#cancelWaterReminders, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i6.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NotificationSettings> getSettings(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, [userId]),
            returnValue: _i4.Future<_i2.NotificationSettings>.value(
              _FakeNotificationSettings_0(
                this,
                Invocation.method(#getSettings, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.NotificationSettings>);

  @override
  _i4.Future<void> saveSettings(
    String? userId,
    _i2.NotificationSettings? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [userId, settings]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
